### ISSUE TITLE
I installed a plugin in Dynatrace 6.3 but the database type is still Oracle and MSSQL only

### ISSUE THREAD

**Issue by sheh1000** [dynaTrace/Dynatrace-PostgreSQL-Monitor-Plugin#1]
Hello,

I installed plugin but in the drop-down list the PostgreSQL type is not available.
![Imaget](http://pix.academ.info/img/2016/06/09/512eaeace1689a90c5f254c8e04dcad8.png)

May be you can tell what could I did wrong?

**Comment by ghost** [comment]
Hi 
this plugin is a monitor. You have to use it from the System Profile, in the "Monitors" topic...
See https://community.dynatrace.com/community/display/DOCDT63/System+Profile+-+Monitors
